### ISSUE TITLE
packages-required-stable-4.11.tar.gz and packages-required-master.tar.gz need to be updated

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap-distribution#102]
`packages-required-stable-4.11.tar.gz` and `packages-required-master.tar.gz` need to be updated. They contain outdated versions of GAPDoc, smallgrp, primgrp -- this recently bit me, when code started to fail when I switch from a full to a minimal bootstrap because of the outdated GAPDoc.

**Comment by alex-konovalov** [comment]
Thanks for reminding me that someone uses a  minimal bootstrap!

**Comment by alex-konovalov** [comment]
Updated `packages-required-master.tar.gz` and `packages-required-stable-4.11.tar.gz`.
