### ISSUE TITLE
Automate updated of packages-required-BRANCH.tar.gz

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap-distribution#103]
If new package releases of the four (for now) required packages are picked up, then we should make sure that `packages-required-BRANCH.tar.gz` gets updated for all active branches. Ideally, this would be done fully automatically by a script running on Travis / GitHub Actions / Jenkins / whatever.

See also issue #102.

**Comment by alex-konovalov** [comment]
Looked at this. Actually, https://github.com/gap-system/gap-distribution/blob/master/DistributionUpdate/PackageUpdate/Makefile already has targets `pkg-required-stable` and `pkg-required-master`, but they were not called in Jenkins, which only calls `pkg-stable` and `pkg-master` targets from this Makefile. Added the call to Jenkins, so the next run should build new required package archives.

**Comment by alex-konovalov** [comment]
Updated `packages-required-master.tar.gz` and `packages-required-stable-4.11.tar.gz`.
