### ISSUE TITLE
Package permissions

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap-distribution#11]
We check currently for non-standard permissions in package archive at the release wrapping stage, where it may be too late to ask package authors to fix them. 

It will be better to check for permissions when the new version of the package is picked up.

**Comment by Stefan-Kohl** [comment]
Why are file permissions not fixed when wrapping a release?

**Comment by alex-konovalov** [comment]
That's our policy: for core system, we check and fix them with https://github.com/gap-system/gap-distribution/blob/master/DistributionUpdate/fixpermissions script, but for packages we only report them with https://github.com/gap-system/gap-distribution/blob/master/DistributionUpdate/checkpermissions.

We believe that if package authors provided a package with certain permissions, there may be a reason (perhaps known only to them) to do that.

For example, `atlasrep/tst/docxpl.tst` has the permissions 444. When I reported that, I've learned that this file is created/replaced automatically by GAPDoc, so the idea is that with permission 444 one gets a hint if one occasionally wants to edit that file.

**Comment by Stefan-Kohl** [comment]
Is there a better example? -- Just for the purpose of reminding not to edit an automatically generated file, it would suffice to add a comment at the beginning.

**Comment by alex-konovalov** [comment]
We may call `chmod -R a+r pkg` while wrapping release. This was we will respect other choices made by authors regarding permissions, but will ensure that all files are world-readable.

**Comment by alex-konovalov** [comment]
So, I see two TODOs coming from this:
* call `chmod -R a+r pkg` to make all files in packages word readable (this will not challenge any other permission choices by package authors)
* edit https://github.com/gap-system/gap-distribution/blob/master/DistributionUpdate/checkpermissions to produce more visible warnings for non world-readable files in GAP packages

**Comment by Stefan-Kohl** [comment]
Will the `chmod -R a+r pkg` then be done for the 4.8.3 release?

**Comment by alex-konovalov** [comment]
@Stefan-Kohl probably. I've added the check for non-world-readable files in https://github.com/gap-system/gap-distribution/commit/8af3b30e0fbe84b26daf7ee72218b3529ede2816 and in the current set of packages all problems reported before are gone, but one more is detected
```
Files which are not world readable:
+ find . -type f '!' -perm -004 -printf '%m %p\n'
600 ./gap4r8/pkg/grape/nauty22/naututil.h
600 ./gap4r8/pkg/grape/nauty22/gtools.h
```
This is GRAPE from 4.8.2 release, but because these files are not required when it loads, this was unnoticed before.

**Comment by alex-konovalov** [comment]
Resolved by https://github.com/gap-system/gap-distribution/commit/4ce1e7e7aacdd73ca3357f931a6e9836a1c87677 which ensures that all files in packages distributions are world-readable.
