### ISSUE TITLE
Revise packages with precompiled binaries for Windows installer

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap-distribution#21]
Check if we can provide more packages with precompiled binaries - both with kernel modules and with stand-alone executables.

**Comment by alex-konovalov** [comment]
Probably just using `bin/BuildPackages.sh` will lead to many improvements.

**Comment by ChrisJefferson** [comment]
I found many more things compiled. The big one that it seems doesn't is grape -- I'm not sure how (or if) you've handled it before, but nauty doesn't build on cygwin due to it's configure script being too old.

**Comment by alex-konovalov** [comment]
Grape's binary were not compiled locally, but came in the Grape archive provided by Leonard. Last time in January 2016.

**Comment by alex-konovalov** [comment]
In GAP 4.8.7, Windows binaries for packages are built with `bin/BuildPackages.sh` script. I will monitor the situation, which will change for GAP 4.9 anyway.
