### ISSUE TITLE
Get rid of `DistributionUpdate/fixpermissions`

### ISSUE THREAD

**Issue by fingolfin** [gap-system/gap-distribution#26]
The script `DistributionUpdate/fixpermissions` currently is out of date -- and even if we update it, it likely will get out of sync with reality again and again in the future.

As it is, I don't see the point of this script these days: git tracks the executable bit for us.

**Comment by alex-konovalov** [comment]
Thanks, I am aware that https://github.com/gap-system/gap-distribution/blob/master/DistributionUpdate/fixpermissions (this is also related to #22 which mentions another place where some files that already disappeared are still mentioned).

I will think if we can get rid of it. What prevents me from saying yes immediately is that is is not used in the clone of the repository - instead it is used later, after it had been archived and unpacked elsewhere (see https://github.com/gap-system/gap-distribution/blob/master/DistributionUpdate/doit). So this could be considered as an extra check to ensure that the permissions are right.

**Comment by alex-konovalov** [comment]
@fingolfin you're right - I should replace it by checking permissions instead of adjusting them. It will be easier to maintain it too!

**Comment by alex-konovalov** [comment]
Checks are actually already done later in `checkpermissions` script. So I've removed `fixpermissions` completely in 5718cd2b724750a4f712a1f3ad24588982ca38cf.
