### ISSUE TITLE
Alternative distros: homebrew

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap-distribution#46]
To remind me of https://github.com/Homebrew/homebrew-core/pull/21928 to be revisited when GAP 4.9.1 will be out.

**Comment by alex-konovalov** [comment]
Thank you @sjackman - good to know about it for my bioinformatics friends! GAP seem to be fitting Homebrew/core better - it's a system for computational discrete mathematics. I need to address feedback at https://github.com/Homebrew/homebrew-core/pull/21928 and want to combine that with the new release of GAP 4.9 which may require some changes there, hence the delay.

**Comment by alex-konovalov** [comment]
We have now a Homebrew tap at https://github.com/gap-system/homebrew-gap

**Comment by sjackman** [comment]
For others that stumble onto this issue, install `gap` from this tap using:
```sh
brew install gap-system/gap/gap
```
