### ISSUE TITLE
Missing http in URLs in PackageInfo.g files

### ISSUE THREAD

**Issue by alex-konovalov** [gap-system/gap-distribution#5]
Some packages do not have `http://` in the URLs specified in `PackageInfo.g` files, e.g. they have
```
WWWHome       := "place.somewhere.com/~username",
```
instead of 
```
WWWHome       := "http://place.somewhere.com/~username",
```
Package overview pages are generated automatically using these details from PackageInfo.g files, and missing `http` results in broken links as they are interpreted as pointing to local files on the web-server.

Either `http://` should be required in URLs and `ValidatePackageInfo` should check for that, or the website generating scripts should be updated to add `http://` when it is missing.

**Comment by fingolfin** [comment]
I think we should require this... Anyway, can you perhaps (easily?) provide a list of packages that are actually affected?

**Comment by frankluebeck** [comment]
I would consider a missing `http://` or `https://` in such URL as a bug.

**Comment by fingolfin** [comment]
Good, so we kind of agree -- then we should make `ValidatePackageInfo` stricter on this (that's quite easy to do, luckily :-)

**Comment by alex-konovalov** [comment]
Thanks - I agree with considering this a bug and will work on this.

**Comment by alex-konovalov** [comment]
See https://github.com/gap-system/gap/pull/505 - incomplete URLs are given the following packages:
* modules, ringsforhomalg
* itc
* liepring
* semigroups
* sglppow

**Comment by alex-konovalov** [comment]
TODO for myself: check and remind package authors if required.

**Comment by fingolfin** [comment]
Well, getting @mohamed-barakat and @james-d-mitchell to change their packages hopefully won't be a problem :)

**Comment by alex-konovalov** [comment]
* modules, ringsforhomalg - fixed on Github
* semigroups - PR submitted
* liepring, sglppow - reminder sent by email.
