### ISSUE TITLE
read-only gap-4.10.0/pkg/ctbllib/tst/docxpl.tst

### ISSUE THREAD

**Issue by dimpase** [gap-system/gap-distribution#72]
in GAP 4.10.0 tarball this file is read-only (seems to be the only one, at least in `ctbllib`.

This may cause some interesting script errors --- and we got this on [Sage's ticket on GAP 4.10 and libgap](https://trac.sagemath.org/ticket/22626)

```
-r--r--r-- gap-jenkins/gap-jenkins   35292 2018-11-01 22:56 gap-4.10.0/pkg/ctbllib/tst/docxpl.tst
```

@alex-konovalov @ThomasBreuer - would you like to fix this (in 4.10.1 ?)

**Comment by dimpase** [comment]
@embray - please take note. Yes, I agree that a comment in the header is a more usual way to deal with this.

**Comment by fingolfin** [comment]
To be frank, I don't see how this is a bug in GAP or in ctbllib. It rather seems to be a bug in your scripts for copying files around... ? Dealing with exactly such issues is why `install(1)` exists.

**Comment by dimpase** [comment]
our scripts do not expect files to be read-only, that's for sure...

**Comment by dimpase** [comment]
Who said `install` here? It's a bug in GAP that it does not provide `make install`, though, and so one needs scripts in the 1st place ;-)

**Comment by fingolfin** [comment]
No, lack of `make install` is not a bug. At most it's a missing feature.

And it seems you are writing your own custom install script, but are using `cp` for it, instead of `install`, which would be one way to avoid your issues.
